### PR TITLE
Tweaks

### PR DESCRIPTION
**Pull request by flywire**
Refer commit descriptions

### CODE REVIEW

**Comment by flywire** [comment]
Quick hack to test on Windows:
1. download (current version at https://github.com/flywire/website) and extract to a directory 
2. replace all eight `="/` with =`"./` in index.html
3. double-click index.html to open in browser
4. **delete when finished testing** to avoid uploading because hack is not compatible with live site

**Review by flywire — COMMENTED** [review]
Medium screen layout truncates some wide headings and links in column format

**Comment by lordofbikes** [comment]
* I merged file formatting and wording commits manually.
* The navbar changes need more review, but will be merged soon.
* What's the issue with `min-width:958px`? Is it only the navbar? The current 993px is a common value for responsive websites.
* I can't see a developer biased join us section, the columns were ordered alphabetically.
* I'll work on a better solution for shortening the join us column headers.

**Comment by lordofbikes** [comment]
Use a USB drive to test the site without changes.
When you open `F:\index.html` it should work without changes :wink:

**Comment by flywire** [comment]
> * What's the issue with `min-width:958px`? Is it only the navbar? The current 993px is a common value for responsive websites.

It's basically a communications issue. I was learning how w3.css worked so I changed it to get navbar to display links on medium screens. Once I understood it was using a w3.css template a better fix was ec27319 Navbar icon for small screens - Hamburger icon and c193bbb Navbar varies by screen size - works for medium screens too. I wouldn't change the w3.css framework file now.

**Comment by lordofbikes** [comment]
I finally merged [Shorten words in columns to improve display](https://github.com/LibreCAD/website/pull/6/commits/1744a24d531375a06d1c0518fa4c43cf95145317), which was the last open issue from this PR.
So I close this now.
Many thanks again.

**Pull request closed without merging**
