### PR TITLE
Add PortableApps.com Download

### PR DESCRIPTION
**Pull request by flywire**
Useful install for some community members

### CODE REVIEW

**Comment by dellus** [comment]
That's a great idea. Hopefully also for rc's, betas, nightlies...Perfect for testing...

**Comment by DuncanLithgow** [comment]
@lordofbikes @rvt any reason not to do include this link in the website?

**Comment by DuncanLithgow** [comment]
@fa201 is this one for you? @flywire any interest in making an RC2 version? It looks like the RC1 which you have already made is missing.

**Comment by flywire** [comment]
> It looks like the RC1 which you have already made is missing.

No, it's hosted on my Google Drive<sup>*</sup> which is linked from forum topics at PortableApps [LibreCAD Portable 2.2.0-rc1](https://portableapps.com/node/61725) and LibreCad [portable version of LC](https://forum.librecad.org/portable-version-of-LC-tp5712598p5718516.html).

PortableApps will not support pre-releases - see [explaination](https://portableapps.com/node/61720)

> We don't normally update to pre-releases, we only do stable releases. And it's based on what the publisher makes available. I'm wondering if other LibreCAD users would like to chime in on whether we should make an exception in this case.

> Talk to the publisher. They have 2.1.3 indicated as their official stable release. If they switch it to the 2.2.0 RC (which is labeled specifically as a Pre-Release) we'd update it.

LibreCad was requested to put up a case if they wanted this changed. In my view what LibreCad put out as a pre-release every other organisation puts out as a release.

---

Version updates are easy.

Copy latest release, unzip to a new folder, rename folder to remove `.paf`

> ... simply:
>
> * replacing the LibreCADPortable_2.1.3\App\LibreCAD folder with the one from C:\Program Files (x86)\LibreCAD
> * updating LibreCADPortable_2.2.0-rc1\App\AppInfo\appinfo.ini

then run through `PortableApps.comInstaller.exe`.

---

<sup>*</sup> A better solution would be for LibreCad to build and host it's PortableApps, including nightly builds. I asked about [Maintaining a PortableApp on GitHub](https://portableapps.com/node/61880) but didn't get a useful reply. Random people like me hosting the software is unreasonable.

**Comment by flywire** [comment]
[LibreCAD Portable 2.2.0-rc2](https://portableapps.com/node/63458)

**Comment by DuncanLithgow** [comment]
there are currently two critical bug before a final release https://github.com/LibreCAD/LibreCAD/projects/1

**Comment by flywire** [comment]
> there are currently two critical bug before a final release https://github.com/LibreCAD/LibreCAD/projects/1

This is irrelevant to this issue, despite the issue being closed (fixed?) before the comment.

**Comment by lordofbikes** [comment]
I wrestled with myself, but i have decided that the home page is not the right place to link to PortableApps.
I understand the advantages of the portable version, but I still see it as a special case if someone needs it.
In my opinion, a link on the homepage would give the impression that this installer is official and equivalent to our setup. But that is not the case and I fear that this will cause more problems than solutions.

PortableApps is an independent platform with a decent level of awareness. If someone needs the portable version, they will find it that way too. In addition, it has been mentioned often enough in the forum that it can also be found via it.

Many thanks anyway.

**Pull request closed without merging**
