### PR TITLE
Display Navbar Menu Icon if not Large Screen

### PR DESCRIPTION
**Pull request by flywire**
Excludes:
c2baa5b Show navbar links on narrower windows - change to w3.css framework is a bad idea

Includes:
ec27319 Navbar icon for small screens - Hamburger icon
c193bbb Navbar varies by screen size - works for medium screens too
8413025 Consistent 4 space indents

### CODE REVIEW

**Comment by lordofbikes** [comment]
This time the visible menu is right aligned again, so everything look fine.
Many thanks!

**Comment by flywire** [comment]
Tried to tweak it so if the user accidentally hit the logo to return home while the icon menu was open it closed the icon menu. Unfortunately (through further testing) `myFunction()` toggles icon menu so clicking the lc logo opened the icon menu when it was closed.

Does `myFunction()` allow passing a parameter to just close the icon menu?

**Comment by lordofbikes** [comment]
I beautified your contribution and added the parameter to re-enable the logo for closing the small menu.
See https://github.com/LibreCAD/website/commit/ef9ff11ba0c77746944652aaa881df0f1ff1a9a5

**Comment by flywire** [comment]
Nice, I see it took a bit of work. How does the gh repository get to [librecad.org](https://librecad.org)?

**Comment by lordofbikes** [comment]
Manual pull from the server, nothing automated yet.

**Pull request merged**
